### ISSUE TITLE
std::out_of_range error in CEE debug build

### ISSUE THREAD

**Issue by gahansen** [gahansen/Albany#258]
Added a new CDash nightly build, an explicit DEBUG build, using gcc 7.2.0, called "Albany64BitDbg." Have 3 failing tests:

Parallel_Dynamic_Cubes_NewmarkExplicitAForm_LumpedMass_Tempus
Dynamic_ClampedSDBC_NewmarkExplicitAForm_Tempus
Schwarz_Cubes

with the error:

p=3: *** Caught standard std::exception of type 'std::out_of_range' :

 /projects/AppComp/nightly_gahanse/cee-compute011/test/TrilinosDbg/include/Thyra_ModelEvaluatorHelpers.hpp:544:
 
 Throw number = 1
 
 Throw test that evaluated to true: (inArgs.modelEvalDescription()) != (modelEvalDescription)
 
 Error, (inArgs.modelEvalDescription() = Thyra::DefaultModelEvaluatorWithSolveFactory{thyraModel='Albany::ModelEvaluatorT',W_factory='Thyra::AztecOOLinearOpWithSolveFactory{precFactory=Thyra::Ifpack2PreconditionerFactory}'}) != (modelEvalDescription = Piro::InvertMassMatrixDecorator<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >)!

I seem to recall seeing something like this on an unrelated test in the very distant past, that @ibaned might have tracked down and fixed. I might engage @tjfulle in a discussion on this if no one has comments.

**Comment by ikalash** [comment]
Interesting.  Is this a new nightly build?  I have one idea of how to fix this.  Can you please recompile Trilinos and Albany with packages/piro/src/Piro_InvertMassMatrixDecorator_Def.hpp over-written with the attached file to see if it fixes the problem?  
[Piro_InvertMassMatrixDecorator_Def.hpp.txt](https://github.com/gahansen/Albany/files/1683498/Piro_InvertMassMatrixDecorator_Def.hpp.txt)

**Comment by ikalash** [comment]
I just reproduced the error on algol, which has the same compiler, and verified that my fix resolves the issue.  I cannot push to Trilinos using the checkin script, however, as there is some compilation error in Panzer which has a Piro dependency:
```
[ 54%] Building CXX object packages/panzer/disc-fe/src/CMakeFiles/panzer-disc-fe.dir/Panzer_BlockedVector_ReadOnly_GlobalEvaluationData.cpp.o
In file included from /scratch/ikalash/remote_trilinos_base_dir/Trilinos/packages/panzer/disc-fe/src/Panzer_EquationSet_DefaultImpl_impl.hpp:62:0,
                 from /scratch/ikalash/remote_trilinos_base_dir/Trilinos/packages/panzer/disc-fe/src/Panzer_EquationSet_DefaultImpl.cpp:50:
/scratch/ikalash/remote_trilinos_base_dir/Trilinos/CHECKIN/MPI_RELEASE_DEBUG_SHARED_PT/packages/panzer/disc-fe/src/Panzer_Sum.hpp:1:31: fatal error: Panzer_Sum_decl.hpp: No such file or directory
 #include "Panzer_Sum_decl.hpp"
```
(@rppawlo , are panzer folks aware of this?).  I'll push as soon as the panzer issue is resolved and the checkin script lets me push.

**Comment by rppawlo** [comment]
@ikalash - try wiping your build directory. Three weeks ago this file was changed from using the Trilinos ETI mechanism. The old ETI autogenerated file still exists in your build directory and it is screwing up the build.

**Comment by ikalash** [comment]
Ah OK.  I admittedly hadn't pushed to Trilinos for awhile, but things seem to get broken pretty often so I thought it might be a legitimate build error.  Running the checkin script now.

**Comment by ikalash** [comment]
@gahansen : my fix just got pushed to Trilinos develop branch (https://github.com/trilinos/Trilinos/commit/5a4279d7eb50c1359268989b3e9aad7f8e4380e3 ).  Please let me know if it does not remedy this problem.

**Comment by gahansen** [comment]
@ikalash - sorry that I have not been able to get back to this until now. I'll watch that dashboard in the morning and report back. 

Yes, this is a new nightly test target on our dashboard at:

http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&subproject=Albany64BitDbg

I strategized that it might be a good idea to have a debug build using a -- very recent -- gcc, if only to allow others to access the build on a CEE server to facilitate rapid debugging.

**Comment by ikalash** [comment]
No worries.  I think having a debug build on the dashboard is a great idea.  I know @lxmota used to have nightly debug builds but I think none of the ones on CDash are.  I'll check the CDash tomorrow morning too to see if this is resolved.  

Note that my fix will not remedy Schwarz_Cubes, which also is failing in the new debug build.  I looked at the output on cee-compute020 and there is a Teuchos::DanglingReferenceError, it looks like.  I'll try to see what is going on there.  The verbose output for this failure should get pushed to CDash tomorrow and we can open a new issue if I don't fix it by then.

**Comment by ikalash** [comment]
It looks like my patch to Piro fixed the problem, looking at the CDash outcomes from last night.
