### ISSUE TITLE
Compilation / link errors for clean Albany build with no Epetra; failing MOR tests with Epetra; failing FELIX tests on CUDA Kokkos node

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#326]
It seems there are some compilation/link errors when building Albany from scratch using my nightly scripts, see:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=73467
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=73453

I think it has to do with the merge earlier today.  @bartgol , @mperego , can you please have a look?

**Comment by ikalash** [comment]
@bartgol : OK, sounds good.  I did update Trilinos, yes.  It looks like the link error is only in the no-Epetra build: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=73519 .  The other build error seems to have gone away, not sure why.  

Note also that there are 3 failing MOR tests in the with-Epetra build:

```
        342 - MOR_MechanicalCube_FOM (Failed)
	343 - MOR_MechanicalCube_RB (Failed)
	344 - MOR_MechanicalCube_PGROM (Failed)
```
It's really the first one that is failing (the 2nd too test depend on it), I think.  All that is supposed to do is run a regular mechanics problem (FOM = full order model).  It seems the nonlinear solver is diverging now.

**Comment by mperego** [comment]
Commit 7947d2d should fix the link error with the Epetra-free build.
Not sure about the failing MOR tests though.

**Comment by jewatkins** [comment]
It looks like the following cuda tests are failing too:
```
FO_GIS_GisUnstructuredTpetra | Failed | 2m 22s 100ms | Completed (Failed)
FO_GIS_GisAdjointSensitivityTpetra | Failed | 25m  10ms | Completed (Timeout)
FO_GIS_GisSensSMBwrtBetaTpetra | Failed | 25m  10ms | Completed (Timeout)
```
with the following error at the end of program execution:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaFree(m) error( cudaErrorCudartUnloading): driver shutting down /home/projects/albany/build/TrilinosInstall/include/Sacado_DynamicArrayTraits.hpp:233
Traceback functionality not available
```
It looks like they're new tests that weren't tested before. I can see if I can get some better information on the error.

**Comment by mperego** [comment]
Yes, I added them to test the adjoint sensitivities. Thanks @jewatkins for looking into that!

**Comment by ikalash** [comment]
Just to follow up: the MOR tests are still failing.  If you look at the MOR_MechanicalCube_FOM test output, here is what happens: 

```
1: ||F|| = 0.000e+00  step = 0.000e+00  dx = 0.000e+00 (Converged!)
1: ||F|| = 1.513e+03  step = 0.000e+00  dx = 0.000e+00
1: ||F|| = 1.057e+03  step = 1.000e+00  dx = 2.255e-02
1: ||F|| = 3.208e+02  step = 1.000e+00  dx = 2.843e-02
1: ||F|| = 2.614e+02  step = 1.000e+00  dx = 1.354e-02
1: ||F|| = 2.648e+02  step = 1.000e+00  dx = 1.595e-02
1: ||F|| = 3.193e+02  step = 1.000e+00  dx = 2.325e-02
1: ||F|| = 3.582e+02  step = 1.000e+00  dx = 4.060e-02
1: ||F|| = 4.052e+02  step = 1.000e+00  dx = 6.931e-02
1: ||F|| = 3.974e+02  step = 1.000e+00  dx = 1.073e-01
1: ||F|| = 5.491e+02  step = 1.000e+00  dx = 1.749e-01
1: ||F|| = 5.572e+02  step = 1.000e+00  dx = 2.413e-01
1: ||F|| = 1.039e+03  step = 1.000e+00  dx = 3.973e-01
1: ||F|| = 5.702e+02  step = 1.000e+00  dx = 3.118e-01
1: ||F|| = 5.577e+02  step = 1.000e+00  dx = 1.998e-01
1: ||F|| = 8.087e+02  step = 1.000e+00  dx = 2.902e-01
1: ||F|| = 7.513e+02  step = 1.000e+00  dx = 3.342e-01
1: ||F|| = 5.632e+02  step = 1.000e+00  dx = 3.656e-01
1: ||F|| = 1.115e+03  step = 1.000e+00  dx = 4.960e-01
1: ||F|| = 6.820e+02  step = 1.000e+00  dx = 4.342e-01
1: ||F|| = 7.399e+02  step = 1.000e+00  dx = 4.727e-01
1: ||F|| = 1.234e+03  step = 1.000e+00  dx = 6.761e-01
1: ||F|| = 1.361e+03  step = 1.000e+00  dx = 6.644e-01
1: ||F|| = 2.289e+03  step = 1.000e+00  dx = 6.289e-01
1: ||F|| = 1.050e+03  step = 1.000e+00  dx = 2.594e-01
1: ||F|| =      -nan  step = 1.000e+00  dx = 4.240e+00 (Failed!)
```

As I said on the Albany concall, the nonlinear solver seems to diverge now; not sure why.  This test is just running the full order mode, so just a 'Mechanics 3D' problem, like any regular LCM test.  One difference is MOR uses the Albany (Epetra) executable, unlike LCM - might be a clue.  The test ran correctly early Friday morning (http://cdash.sandia.gov/CDash-2-3-0/testSummary.php?project=10&name=MOR_MechanicalCube_FOM&date=2018-07-13), so the problem started with the merge/PR that occurred on Friday.

**Comment by ikalash** [comment]
Update: I am pretty sure it's an issue with the Albany (Epetra) exe vs. the AlbanyT (Tpetra) exe.  The full order model (FOM) for MOR can run with AlbanyT, so I tried running the problem with AlbanyT after switching to Ifpack2 as a preconditioner.  The test runs correctly without the solver diverging.  We could switch the test to Tpetra but we should probably figure out what's going wrong with the original Epetra test.  Also, it seems the MOR_MechanicalCube_PGROM test (which must be run with Epetra) fails nontrivially even if switching the FOM test on which this test depends to Tpetra.  I'll pass this off to @bartgol to continue looking into.

**Comment by ikalash** [comment]
@bartgol : it occurred to me that it could be Trilinos.  It seems it would be somewhat of a coincidence given the timing of your merge, but, hey, it could happen (I've seen it before where we push a big Albany change that seems to break things when it's really Trilinos).  I did notice looking at the MOR tests that there has been some weirdness in the output for awhile.  

For example, for this test: http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3794377&build=73467 , there are Kokkos and Tpetra-related errors

```
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_host" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "DualView::modified_device" is being deallocated after Kokkos::finalize was called.
WARNING: Tpetra::Map destructor (~Map()) is being called after Kokkos::finalize() has been called.  This is user error!  There are two likely causes: 
  1. You have a static Tpetra::Map (or RCP or shared_ptr of a Map)
  2. You declare and construct a Tpetra::Map (or RCP or shared_ptr of a Tpetra::Map) at the same scope in main() as Kokkos::finalize() or Tpetra::finalize().
Don't do either of these!  Please refer to GitHib Issue #2372.
Kokkos allocation "FixedHashTable::pairs" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "FixedHashTable::ptr" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
Kokkos allocation "lgMap" is being deallocated after Kokkos::finalize was called
This behavior is incorrect Kokkos usage, and will crash in future releases
```
For this test: http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=3794378&build=73467 , there are some messages printed about the nonlinear solver failing to converge even though the test was passing until Friday.  That seems fishy.

I'm not sure how long these messages have been present in the output (though one could probably figure it out looking at the CDash site).  Tagging @plindsa , the author of the MOR tests.  Payton, I know you don't work on MOR anymore, but perhaps you can communicate this info to whoever took over this stuff after you moved to 1500.

**Comment by bartgol** [comment]
It is odd to see that message, since all the stuff in Main_Solve.cpp that needs kokkos is wrapped in a try-catch block.

**Comment by bartgol** [comment]
Ah, Main_RBGen.cpp does create stuff that requires Kokkos at the same scope of Kokkos::initialize/finalize, but does not clean up before calling Kokkos::finalize. That would be the cause of the warning/error message.

**Comment by ikalash** [comment]
Oh yes, you are right.  That shows you how stale / unmaintained the MOR stuff is...  Can you please add the finalize, @bartgol , since you are looking at the code?

**Comment by bartgol** [comment]
Yeah, I'll do that.

**Comment by bartgol** [comment]
After bisecting master, I found out that the commit that broke the MOR tests is 7dcdb8f. Now I have to find out why. @mperego , since that's one of your commit, if you can think of anything, let me know.

As for the kokkos-related error/warning, I will push directly to master after testing tomorrow.

**Comment by mperego** [comment]
That's a large commit.
Is the nonlinear solve that is not converging? If so it might be an issue with the computeGlobalResidual or computeGlobalJacobian. However, if that's the case,  it is weird that all the other epetra tests are running fine. @ikalash, can you think of anything peculiar about this test?

Anyway, I'll try to look into that tomorrow. Thanks @bartgol for finding the offending commit.

Best,
Mauro

Sent from VMware Boxer









On Jul 16, 2018 10:47 PM, Luca Bertagna <notifications@github.com> wrote:

After bisecting master, I found out that the commit that broke the MOR tests is 7dcdb8f<https://github.com/gahansen/Albany/commit/7dcdb8f86e50783b0aaa2492c9e723e8d7d1184b>. Now I have to find out why. @mperego<https://github.com/mperego> , since that's one of your commit, if you can think of anything, let me know.

As for the kokkos-related error/warning, I will push directly to master after testing tomorrow.

**Comment by mperego** [comment]
I found the issue. The residual method is also changing the value of the solution (I guess for Dirichlet conditions). So we need to copy the tpetra solution back to the epetra solution after the residual is computed.
The fact that we are doing a cons_cast to modify a const vector is not ideal.. we should probably change the computeGlobalResidual signature to warn that the solution might be changed.
Anyway, I'll commit a fix sometime today.

**Comment by ikalash** [comment]
That's great, @mperego .  Sorry for the delay in my response - I was in a tutorial this morning.  I was planning to say that the fact that the issue showed up with Albany not AlbanyT suggested it was a problem in the Epetra routines within the code.  It sounds like this is what it was indeed.  I'll keep an eye out for your fix.

**Comment by mperego** [comment]
I think commit f9f999e fixes the problem. I’m closing the issue.
@ikalash, note that the `computeGlobalJacobianT`
was never calling `computeGlobalJacobianSDBCsImplT`.
I fixed it now and all the tests I tried (MOR, FELIX, LCM, ATO)
work fine.

**Comment by ikalash** [comment]
Thanks, @mperego !

**Comment by plindsa** [comment]
Thanks from me as well!
