### ISSUE TITLE
Failing CISM-Albany tests due to changes to Neumann BC PL syntax

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#383]
All the CISM-Albany tests are failing due to changes to the Neumann BC PL syntax ,e.g., 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4055423&build=77985

@bartgol , I will try to figure out how to map the old PL syntax to the new one.  I may bug you if I have questions/issues.

**Comment by ikalash** [comment]
@bartgol : I started looking at how to fix the CISM-Albany tests and it appears there is an issue.  Has the 'basal_scalar_field' option for the NBC been removed as these lines from your PR suggest:
```
- enum NEU_TYPE {COORD, NORMAL, INTJUMP, PRESS, ROBIN, BASAL, BASAL_SCALAR_FIELD, TRACTION, LATERAL, CLOSED_FORM, STEFAN_BOLTZMANN};
+  enum NEU_TYPE {COORD, NORMAL, INTJUMP, PRESS, ROBIN, TRACTION, CLOSED_FORM, STEFAN_BOLTZMANN};
```
I was using that NBC in the CISM-Albany interface.  Here is how: https://github.com/gahansen/Albany/blob/master/src/LandIce/interface_with_cism/ali_driver.cpp#L506 .  Basically I want to pass to the NBC a pointer to an array containing the values of the (spatially-varying) basal friction field, which comes from CISM.  Is it still possible to do this with the new redesigned LandIce BCs?

**Comment by bartgol** [comment]
Anything you could do before is still possible now, sometimes via Neumann BCs, sometimes via LandIce BCs. In the case of scalar field basal bc, we have to use landice-specific stuff. I will fixx cism sometime this week.

**Comment by ikalash** [comment]
Oh ok that would be great.  I’m happy to test once you fix it.

**Comment by bartgol** [comment]
Ok, the fix _seemed_ quick, so I pushed directly to master. I'm not sure if there's more to it, though, so this fix needs to be checked. I think we can wait tomorrow's dash to see.

**Comment by ikalash** [comment]
Great!  I am flying today so let’s just wait to see what the nightlies tomorrow reveal.

**Comment by ikalash** [comment]
Unfortunately @bartgol your fix didn't remedy this issue.  I made another fix just now having to do with getting the PL options read in correctly.  Now there's an exception thrown:
```
1: In ali_driver: creating Albany mesh struct...
1: Proc #0, NumNodes = 8820, NumEles = 3892, NumBasalFaces = 973, NumWestFaces = 140, NumEastFaces = 140, NumSouthFaces = 140, NumNorthFaces = 140
1: terminate called after throwing an instance of 'std::logic_error'
1:   what():  /home/ikalash/nightlyCDash/repos/Albany/src/LandIce/problems/LandIce_StokesFOBase.cpp:93:
1: 
1: Throw number = 1
1: 
1: Throw test that evaluated to true: meshSpecs[0]->sideSetMeshSpecs.find(ssName)==meshSpecs[0]->sideSetMeshSpecs.end()
1: 
1: Error! Either the side set name is wrong or something went wrong while building the side mesh specs.
1: 
```
Do you know why this might be happening?  The sideset names should be correct (they worked with the old Neumann BCs).

**Comment by bartgol** [comment]
I know what's wrong. Ninja-fix coming soon.

**Comment by ikalash** [comment]
Test are still failing.  I will comment with more information shortly.  Lets keep this issue open until the nightly tests reveal that the tests are indeed fixed.

**Comment by ikalash** [comment]
@bartgol : now it looks like it's not finding the "Type" of the BC 0 even though that is clearly set: 
```
In ali_driver: creating Albany mesh struct...
terminate called after throwing an instance of 'Teuchos::Exceptions::InvalidParameterName'
  what():  Error!  The parameter "Type" does not exist
in the parameter (sub)list "Albany Parameters->Problem->LandIce BCs->BC 0".
The current parameters set in (sub)list "Albany Parameters->Problem->LandIce BCs->BC 0" are:
  {
  }
Throw number = 1
```
and http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4063981&build=78159 .

Perhaps the code tries to get the "Type" somewhere before it is set in ali_driver.cpp?

What's kind of weird is when I run sometimes this error occurs, other times it does not.  I think there are more problems upstream of this with a failure to meet dependencies based on those tests, but lets try to fix this issue first.

**Comment by bartgol** [comment]
Oh, I made a silly mistake. Bug fix coming.

**Comment by ikalash** [comment]
Thanks @bartgol .  It looks like now there is the failure to meet dependencies error I mentioned earlier.  I'm attaching the error.jpg graph file.  Looks like DOFInterpolationSide isn't getting basal_friction_Basal.

**Comment by ikalash** [comment]
![error](https://user-images.githubusercontent.com/7018124/48498885-0b23e500-e7ec-11e8-870a-935445c74a11.jpg)

**Comment by bartgol** [comment]
Ah, I think once we put in the branch with the fixes for the mpas interface, this error will go away. I think @mperego is doing the final tests for that branch, so it should be good to go soon.

**Comment by ikalash** [comment]
I see.  I'll keep an eye out for that PR.

**Comment by ikalash** [comment]
I just pushed a fix on the CISM side that brings the tests status back to passing.  Thanks @mperego and @bartgol for working on resolving the problem!
